# Generated by Django 4.2.5 on 2023-12-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0003_item_quantity_alter_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(default="Normal", max_length=250),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(
                blank=True,
                default="The <django.db.models.fields.CharField>",
                max_length=250,
                null=True,
            ),
        ),
    ]
