# Generated by Django 4.2.5 on 2023-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0004_item_status_alter_item_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
        migrations.AddField(
            model_name="item",
            name="age",
            field=models.FloatField(default=70),
        ),
    ]
